#!/bin/bash
# Converts GLTF/GLB models to Svelte components using @threlte/gltf.
# Recursively finds every directory under ./obj/ that contains .gltf/.glb (e.g. obj/mobs/bigs),
# creates matching output under client/src/lib/models/generated/<subdir> and client/static/models/<subdir>,
# so paths like obj/mobs/bigs/ and obj/mobs/flyers/ become generated/mobs/bigs/, static/models/mobs/bigs/, etc.
# Run from project root: ./scripts/build-models.sh

set -e

# Project root (script lives in scripts/)
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
export PROJECT_ROOT
GLTF_DIR="$PROJECT_ROOT/obj/"

# Guard: obj must exist
if ! [ -d "$GLTF_DIR" ]; then
  echo "No $GLTF_DIR directory. Nothing to do."
  exit 0
fi

cd "$PROJECT_ROOT/client"

# Find every directory under obj/ that has at least one .gltf or .glb (direct children), including nested (e.g. obj/mobs/bigs)
shopt -s nullglob
content_dirs=""
while IFS= read -r -d '' d; do
  for f in "$d"/*.gltf "$d"/*.glb; do
    [ -f "$f" ] && { content_dirs="${content_dirs}${d}"$'\n'; break; }
  done
done < <(find "$GLTF_DIR" -type d -print0 2>/dev/null)
content_dirs=$(echo "$content_dirs" | sort -u)

for subdir_path_raw in $content_dirs; do
  [ -d "$subdir_path_raw" ] || continue
  subdir_path="${subdir_path_raw}/"
  # subdir = path relative to obj (e.g. mobs/bigs, castle_props)
  subdir="${subdir_path#$GLTF_DIR}"
  subdir="${subdir%/}"

  OUTPUT_SVELTE="$PROJECT_ROOT/client/src/lib/models/generated/$subdir"
  OUTPUT_GLB="$PROJECT_ROOT/client/static/models/$subdir"
  mkdir -p "$OUTPUT_SVELTE" "$OUTPUT_GLB"

  # Collect .gltf and .glb in this subdir (same level only)
  count=0
  total=0
  for f in "${subdir_path}"*.gltf "${subdir_path}"*.glb; do
    [ -f "$f" ] && total=$((total + 1))
  done
  [ "$total" -eq 0 ] && continue

  echo "Converting $total models in $subdir..."
  # Run from OUTPUT_SVELTE so @threlte/gltf writes .svelte and -transformed.glb into this dir (not client/ root)
  pushd "$OUTPUT_SVELTE" >/dev/null
  # Depth from generated/<subdir> to project root: 5 + (slashes in subdir + 1) = 6 + slash count
  slash_count=$(echo "$subdir" | tr -cd '/' | wc -c)
  up_levels=$((6 + slash_count))
  INPUT_BASE=$(printf '../%.0s' $(seq 1 $up_levels))"obj/$subdir"
  for gltf in "${subdir_path}"*.gltf "${subdir_path}"*.glb; do
    [ -f "$gltf" ] || continue
    filename=$(basename "$gltf")
    base="${filename%.gltf}"
    base="${base%.glb}"
    count=$((count + 1))
    echo "  [$count/$total] $base"

    # --root sets the path emitted in useGltf (no extra sed; avoid /models/models/)
    npx @threlte/gltf "$INPUT_BASE/$filename" -o . --types --keepnames --meta --root="/models/$subdir/" --transform 2>/dev/null || {
      echo "    Warning: Failed to convert $base"
    }
  done
  # Move transformed GLBs from this dir to static/models/<subdir>
  for g in *-transformed.glb; do
    [ -f "$g" ] && mv "$g" "$OUTPUT_GLB/"
  done
  popd >/dev/null

  # Also move any -transformed.glb the tool wrote next to the source
  for g in "${subdir_path}"*-transformed.glb; do
    [ -f "$g" ] && mv "$g" "$OUTPUT_GLB/"
  done

  # Copy Textures/ (e.g. obj/castle_props/Textures/colormap.png) so GLBs that reference them resolve
  if [ -d "${subdir_path}Textures" ]; then
    cp -r "${subdir_path}Textures" "$OUTPUT_GLB/"
  fi
done

cd "$PROJECT_ROOT"

# Generate model registry from all generated .svelte files under generated/ (subdirs only; no root .svelte)
# key = subdir_snake_case_filename (e.g. mobs/bigs/Demon.svelte -> mobs_bigs_demon, castle_props/tree-large.svelte -> castle_props_tree_large)
# This ensures unique keys even when different subdirs have same filename
to_key() {
  local base="$1"
  local subdir="$2"
  local subdir_prefix=""
  if [ -n "$subdir" ]; then
    # Convert subdir path to snake_case prefix (mobs/bigs -> mobs_bigs_)
    subdir_prefix=$(echo "$subdir" | sed 's|/|_|g' | sed 's/-/_/g' | tr 'A-Z' 'a-z')
    subdir_prefix="${subdir_prefix}_"
  fi
  # Convert filename to snake_case
  local base_key=$(echo "$base" | sed 's/-/_/g' | sed 's/\([A-Z]\)/_\1/g' | sed 's/^_//' | tr 'A-Z' 'a-z' | sed 's/__*/_/g' | sed 's/^_//' | sed 's/_$//')
  echo "${subdir_prefix}${base_key}"
}

REGISTRY="$PROJECT_ROOT/client/src/lib/models/generated-registry.ts"
GENERATED_DIR="$PROJECT_ROOT/client/src/lib/models/generated"
JSON_MANIFEST="$PROJECT_ROOT/server/priv/model_keys.json"

{
  echo "/**"
  echo " * Auto-generated by scripts/build-models.sh - do not edit."
  echo " */"
  echo ""
  echo "export const models = {"
  # Scan every .svelte under generated/ (all subdirs: castle_props, mobs/bigs, etc.). Paths are absolute.
  while IFS= read -r svelte; do
    base=$(basename "$svelte" .svelte)
    dir=$(dirname "$svelte")
    subdir="${dir#$GENERATED_DIR}"
    subdir="${subdir#/}"
    key=$(to_key "$base" "$subdir")
    [ -z "$key" ] && continue
    if [ -z "$subdir" ]; then
      printf "  %s: () => import('./generated/%s.svelte'),\n" "$key" "$base"
    else
      printf "  %s: () => import('./generated/%s/%s.svelte'),\n" "$key" "$subdir" "$base"
    fi
  done < <(find "$GENERATED_DIR" -name "*.svelte" -type f 2>/dev/null | sort)
  echo "};"
} > "$REGISTRY"

# Generate JSON manifest for server
{
  echo "{"
  echo "  \"generated_at\": \"$(date -Iseconds)\","
  echo "  \"keys\": ["
  first=true
  while IFS= read -r svelte; do
    base=$(basename "$svelte" .svelte)
    dir=$(dirname "$svelte")
    subdir="${dir#$GENERATED_DIR}"
    subdir="${subdir#/}"
    key=$(to_key "$base" "$subdir")
    [ -z "$key" ] && continue
    if [ "$first" = true ]; then
      first=false
    else
      printf ",\n"
    fi
    printf "    \"%s\"" "$key"
  done < <(find "$GENERATED_DIR" -name "*.svelte" -type f 2>/dev/null | sort)
  echo ""
  echo "  ]"
  echo "}"
} > "$JSON_MANIFEST"

# Summary (count all .svelte and .glb recursively)
total_svelte=$(find "$GENERATED_DIR" -name "*.svelte" -type f 2>/dev/null | wc -l)
total_glb=$(find "$PROJECT_ROOT/client/static/models" -name "*.glb" -type f 2>/dev/null | wc -l)
echo ""
echo "Done! Generated $total_svelte Svelte components in ./client/src/lib/models/generated/<subdir>/"
echo "Generated $total_glb GLB files in ./client/static/models/<subdir>/"
echo "Registry: $REGISTRY"
